package com.poultry.broiler_farming_system.entity.enums;

public enum NotificationType {
    PAYMENT_APPROVED,
    PAYMENT_REJECTED,
    BATCH_AUTO_COMPLETED,
    BATCH_CYCLE_ENDING_SOON,
    POSTING_EXTENSION_EXPIRING_SOON,
    DAILY_LOG_MISSING,
    MEDICINE_ALARM_DUE,
    FEEDBACK_TICKET_RESOLVED,
    ADMIN_WARNING_ISSUED,
    ACCOUNT_UPGRADE_APPROVED,
    ACCOUNT_UPGRADE_REJECTED
}
